env:
    RCLONE: "ENCRYPTED[eb2e333941bc6d77ce3e1d8f4b8267e863bc61a2eb575e7f8b9d8286df2f4edb8d6e13e2bdd0b2a1c1355be3e480507e]"
    MANIFEST: "https://gitlab.com/OrangeFox/Manifest"
    MANIFEST_BRANCH: "fox_9.0"
    DEVICE: "m32"
    DT_LINK: "https://github.com/twrpdtgen/android_device_samsung_m32"
    DT_PATH: "device/samsung/m32"
    TARGET: "recoveryimage"
    BUILD_TYPE: "eng"
    COMMAND: "git clone https://gitlab.com/OrangeFox/misc/theme bootable/recovery/gui/theme --depth=1"
    COMMAND2: "export ALLOW_MISSING_DEPENDENCIES=true"
    TG_TOKEN: "ENCRYPTED[ba114ab260e16ec1509fdf7feb928222ac87f272d56a7a28ec884582cfe8106d49a7840098af770b34c41d75a618f602]"
    TG_CHAT_ID: "ENCRYPTED[3c07e19a496e2f4a3d35fcf6b48373f9c7b817c20dc10a62c1010881055146fdbf2b569a46f6358280715d3174616281]"
    TZ: "Asia/Dhaka"
    DRIVE: "ENCRYPTED[685c9fecbe7aa2a7a587aa002b8a83d590957011005e972765f43946ed82376d4f8d975ccace8553868ec4e632b24cf0]"

task:
  name: "Recovery-Builder"
  timeout_in: 480m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - mkdir -p /tmp/ccache
       - cd /tmp

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Build_script:
      - bash build.sh
